### ISSUE TITLE
[FEATURE] Use Dev Protocol's Hashi Design System

### ISSUE THREAD

**Issue by MatteuSan** [WebXDAO/devprotocol.xyz#206]
### Detailed description

Use Dev Protocol's new [Hashi Design System](https://github.com/dev-protocol/hashi-web).

### Context

For the platform's consistency's sake, I think we should implement the Hashi Design System to the main website. The system includes design tokens to be used, and the smaller, more primitive components such as buttons, cards, text fields, select fields, etc.

For the larger components, we designed it so that it is up the the project as we believe that those problems have specific design solutions for each project.

The documentation for the design system is located in the repository description :)

(PS: Not really expecting this to be implemented right away, because migration takes time)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vinzvinci** [comment]
Cool, will u able to work on this? Or I'll call someone to help?

**Comment by MatteuSan** [comment]
I don't know if I can work on this since I need to do some prep work for irl stuff (mostly school related). I can probably help if the devs have questions, but for the most part the [documentation](https://hashi-docs.netlify.app) is already ready.

**Comment by vinzvinci** [comment]
Okay. Pinging @AbhinavMV 😁

**Comment by AbhinavMV** [comment]
> Okay. Pinging @AbhinavMV 😁

I will try to do it 😄👍

**Comment by vinzvinci** [comment]
> > Okay. Pinging @AbhinavMV grin
> 
> I will try to do it smile+1

Cool

**Comment by vinzvinci** [comment]
bot ping us 👁️ , what's up with this?
