### ISSUE TITLE
[FEATURE] Stats page for community/protocol 

### ISSUE THREAD

**Issue by aggre** [WebXDAO/devprotocol.xyz#216]
### Detailed description

I suggest adding a stats page to the website to visualize protocol and community activity.

@CryptoDogg and @vinzvinci have already created several data sources, and charts can be placed based on them using [Chart.js](https://www.chartjs.org/), etc.

**Dev Protocol stats**
- Total locked amount (L1+Arbitrum+Polygon... the sum of all networks): Subgraphs = https://github.com/dev-protocol/dev-protocol-subgraphs
- Number of minted DAO tokens: Subgraphs = ??

**Community stats**
- Number of stars on all repositories
- Number of PR/issues on all repositories
- Number of contributors on all repositories

### Context

Dev Protocol has several communication channels ... Discord, Twitter, GitHub, and Telegram, but few people are cross-cutting them. Therefore, statistics showing how the community as a DAO works are a good indicator for many that this project is very active.

### Additional information

_The data sources may be incomplete, or some community statistics ideas may be too difficult to implement._

_This is just the starting point for discussion._

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CryptoDogg** [comment]
The number of proeprty tokens is included in the same subgraph https://github.com/dev-protocol/dev-protocol-subgraphs/tree/main/subgraphs/staking-amount-{l1 or l2}

**Comment by vinzvinci** [comment]
Hi aggre, not all repositories but specific repositories only. Let me see if we can add all repositories for community stats.

**Comment by aggre** [comment]
> Hi aggre, not all repositories but specific repositories only. Let me see if we can add all repositories for community stats.

yes, it's of course no problem! we can done it step-by-step

**Comment by aggre** [comment]
I have created this mock, as a first version of Stats page:
<img width="1152" alt="Mock_ Stats" src="https://user-images.githubusercontent.com/1970283/173268133-d88b1c62-0619-461c-ac7a-ed039a599294.png">

I think, the community stats are can be included next update.

---

BTW: the `See community activities on Discord` button is expected will be replaced with Forem or something

**Comment by vinzvinci** [comment]
> BTW: the `See community activities on Discord` button is expected will be replaced with Forem or something

If it will be replaced by Forem, summary of discussion will be there? Just found this shared by mayu https://dev.to/devteam/a-new-community-space-for-open-source-maintainers-and-contributors-32p3

**Comment by aggre** [comment]
> > BTW: the `See community activities on Discord` button is expected will be replaced with Forem or something
> 
> If it will be replaced by Forem, summary of discussion will be there? Just found this shared by mayu https://dev.to/devteam/a-new-community-space-for-open-source-maintainers-and-contributors-32p3

Yes, I'm thinking that in the future, summaries of updates will be consolidated in a casual forum like Forem.

**Comment by aggre** [comment]
I've deployed TheGraph's Subgraphs for Mainnet, Arbitrum, and Polygon, so the query for the total locked amount is available. The following code is an example for the mainnet. And with changing the value of `skip`, its pagination is available.

```js
fetch('https://api.thegraph.com/subgraphs/name/aggre/devprotocol-mainnet',
  {
    method: 'POST',
    body: JSON.stringify({query: `{
      totalLockedAmounts(first: 100, skip: 0) {
        id
        amount
      }
    }`})
  }
)
.then( res => res.json() )
.then( console.log )
```

And the following endpoints are also available:
- Arbitrum: https://api.thegraph.com/subgraphs/name/aggre/devprotocol-arbitrum-one
- Polygon: https://api.thegraph.com/subgraphs/name/aggre/devprotocol-polygon

---

A subgraph for the total minted DAO tokens will also be deployed later.

**Comment by aggre** [comment]
Here are the completed sample codes for graphing the TVL!

https://jsfiddle.net/aggre/kn9vyrsx/

**Comment by osaguild** [comment]
Hi. I am trying this issue. It is a WIP but I have a few questions. [This is my PR](https://github.com/WebXDAO/devprotocol.xyz/pull/217)
- Adding the total minted DAO token chart takes time. How about making MVP only total locked dev amount.
- The process of getting stats info takes a long time. So I think using scheduled github actions and create the data in a repository is better. If you create the PR with the auto_merge label, some bot can merge pr automatically.

**Comment by aggre** [comment]
> Hi. I am trying this issue. It is a WIP but I have a few questions. [This is my PR](https://github.com/WebXDAO/devprotocol.xyz/pull/217)
> - Adding the total minted DAO token chart takes time. How about making MVP only total locked dev amount.
> - The process of getting stats info takes a long time. So I think using scheduled github actions and create the data in a repository is better. If you create the PR with the auto_merge label, some bot can merge pr automatically. 

@osaguild Great PR!

You can get the data for the total number of minted DAO tokens by replacing `totalStakedAmounts` in the query with `totalAuthenticatedProperties`. FYI, you can test that query here: https://thegraph.com/hosted-service/subgraph/dev-protocol/polygon-v2 (i.g., Polygon)

**Comment by aggre** [comment]
@vinzvinci I know you have been developed a community stats page, can I see their contents in this remote repository?

**Comment by osaguild** [comment]
@aggre Thanks for query info! I will try and update PR.

**Comment by vinzvinci** [comment]
> @vinzvinci I know you have been developed a community stats page, can I see their contents in this remote repository?

Hi aggre, currently this is how it looks, The free trial on airtable was expired so can't use them. I only use mini extensions to create this chart and can be embedded anywhere.
![image](https://user-images.githubusercontent.com/73097560/174722107-67bf11dc-58d5-4d77-b847-b83e09414142.png)

**Comment by vinzvinci** [comment]
Actually, after knowing dework, I'm finding how we can make a graph there and embed it on the website. 

Generalize contributors, not just developers but all community https://app.dework.xyz/devprotocol/contributors
